language: swift
os: osx
osx_image: xcode9.2
cache: cocoapods
xcode_project: PhotoApp.xcodeproj
xcode_scheme: PhotoApp

script:
- export SCAN_DEVICE="iPhone 7 (11.2)"
- export SCAN_SCHEME=PhotoApp
- export SCAN_DERIVED_DATA_PATH=$(pwd)/DerivedData
- fastlane scan
- if [ ! -e MagicPodDesktop0.14.0.zip ]; then curl -L -O https://github.com/Magic-Pod/japanese-issue-and-doc/releases/download/0.14.0/MagicPodDesktop0.14.0.zip; unzip -q MagicPodDesktop0.14.0.zip; fi
- echo -n ${magic_pod_token} > ~/.magic_pod_token
- Magic\ Pod\ Desktop.app/Contents/MacOS/Magic\ Pod\ Desktop run --magic_pod_config=$(pwd)/magic_pod_config.json
